first-version, function play_game almost completed
adamchukyurii/homeworks_for_python pull request #3
Opened 2024-02-20 12:47 UTC by adamchukyurii

2024-02-20 13:10 UTC, PonomaryovVladyslav requested changes
Надо переделывать) не критично но надо, ну и обработки очков вообще нет)

Как первый драфт не плохо

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/game/__pycache__/exceptions.cpython-310.pyc
Файлов пайкеш не должно быть на гите) открой документ про гит и почитай)

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/main.py
> +   if user_choice.lower() == "play":
Шо ж ты над пользователями издеваешься) 1, 2 или 3) и валидация на то что ввели только эти возможные параметры

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/main.py
> +
просто пока не готово?)

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/main.py
> +   player = Player(name, PLAYER_LIVES, 0)
где проверка того что ввел пользователь?) и зачем тебе тут какие либо параметры кроме имени?

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/main.py
> +   return player, "Normal" if mode == "1" else "Hard"
Почему в функции create_player ты спрашиваешь уровень сложности? Как об этом можно вообще догадаться? функция должна делать только то что в ней описано)

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/game/models.py
> +   def __init__(self, name: str, lives: int, score: int) -> None:
нахрена тебе в ините что-то кроме имени? если у тебя очки это всегда 0, а жизни из настроек?

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/game/models.py
> +         user_choice = input("\nChoose a Paper(1), Rock(2) or Scissors(3):\n")
нет проверки на то что ввел пользователь

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/game/models.py
> +         raise GameOver()
или допиши текст в скобки или убери скобки)

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/game/game.py
> +      return enemy
нахрена тут возвращать объект? что тебя останавливает просто записывать новый объект в селф?

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/game/game.py
> +   def __init__(self, player: Player, mode: str) -> None:
отступы между методами не по PEP8

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/game/game.py
> +            self.player.add_score(POINTS_FOR_KILLING)
А где умножение за сложность?)

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/game/models.py
> +      self.level += 1
так себе идея, тебе надо делать новый объект а не кусками переделывать старый))

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/game/game.py
> +         self.play_again()
не надо тут ничего спрашивать просто создаешь нового соперника и все, ну максимум принтишь что нибудь полезное

2024-02-20 13:10 UTC, PonomaryovVladyslav commented on Project_Game/game/usfullfunctions.py
> +   spaces = " " * 19
Если тут стационарные цифры, то это должны быть константы)

2024-02-20 13:31 UTC, adamchukyurii commented on Project_Game/game/game.py
> +         self.play_again()
а как ему присвоить новый уровень, в функции figh чтоли

2024-02-20 16:06 UTC, PonomaryovVladyslav commented on Project_Game/game/game.py
> +         self.play_again()
А зачем ему присваивать новый уровень? Этот умер создай нового

2024-02-23 14:08 UTC, PonomaryovVladyslav requested changes
В телегу все правки накидал)

2024-02-24 16:21 UTC, merged